from pathlib import Path

path = Path('PROJECT_SPEC.md')
text = path.read_text()
old = '4. **STEP 4 — Location/Qibla orchestration: NOT STARTED.** Combine closed Location state with pure bearing and heading state under the Manual-vs-Device live-compass contract. No Location provider changes.'
new = '''4. **STEP 4 — Location/Qibla orchestration: AUTHORIZED / IN PROGRESS.** Introduce an Arihna-owned `QiblaRepository`/equivalent orchestration boundary that consumes only `Flow<LocationResolutionState>`, the closed `QiblaBearingCalculator`, and the closed `DeviceHeadingDataSource`. Use cancellation-aware latest-location semantics (`flatMapLatest`/equivalent) so Device↔Manual and accepted location changes cancel obsolete heading collection and stale sensor/location combinations cannot overwrite the current state. For every valid `LocationResolutionState.Ready`, calculate the bearing from the exact `SelectedLocation.coordinates`; a valid Device `CACHED` location is immediately usable and STEP 4 must not call `LocationCoordinator`, `LocationManager`, request a fresh fix, inspect provider callbacks, DataStore or `CityRepository`. Manual source always yields a static numeric bearing and must make zero heading-datasource subscriptions. Device source may start heading observation with the same accepted coordinates and expose an explicit starting/live/sensor-unavailable state while preserving the calculated static bearing. A heading reading produces `relativeQiblaDirection = normalize(qiblaBearingTrue - deviceHeadingTrue)` and carries through `HeadingQuality`, optional numeric accuracy and `HeadingSource` without fabricating precision. Heading `Unavailable` produces a controlled sensor-unavailable state while keeping the valid numeric bearing. Invalid/coincident bearing results remain controlled and never become `0°`. Non-Ready or invalid Location states produce `NoLocation` and make zero bearing-to-live assumptions. STEP 4 is domain/orchestration only: no Compose, navigation, AppContainer wiring, new permission, dependency, Location behavior, Prayer behavior or sensor algorithm change is authorized. Pure/JVM contract tests must cover every non-Ready state, exact Device/Device-CACHED/Manual coordinate forwarding, Manual zero sensor subscription, Device starting/live/unavailable transitions, relative-angle wrap-around, invalid/coincident bearing handling, Device↔Manual and location replacement cancellation with stale-heading suppression, and proof that no Qibla operation triggers Location refresh/acquisition. Full unfiltered unit regression, `assembleDebug`, Android 9/API28 connected regression and existing policy gates are required before closure. STEP 5 remains **NOT STARTED**.'''
if old not in text:
    raise SystemExit('STEP 4 marker not found')
path.write_text(text.replace(old, new, 1))
